package de.htwg.risiko.controller.impl;

import java.awt.Point;

import de.htwg.risiko.model.ICountry;
import de.htwg.risiko.model.IWorld;
import de.htwg.risiko.model.impl.Country;

final class RiskMap {
	
	private static final ICountry ALASKA = new Country("Alaska", new Point(51, 112));
	private static final ICountry ALBERTA = new Country("Alberta", new Point(99, 148));
	private static final ICountry NORTHWEST_TERRITORY = new Country("Northwest Territory", new Point (120, 104));
	private static final ICountry ONTARIO = new Country("Ontario", new Point (152, 153));
	private static final ICountry WESTERN_US = new Country("Western US", new Point(115, 201));
	private static final ICountry EASTERN_US = new Country("Eastern US", new Point(169, 205));
	private static final ICountry QUEBEC = new Country("Quebec", new Point (216, 158));
	private static final ICountry GREENLAND = new Country("Greenland", new Point(226, 55));
	private static final ICountry CENTRAL_AMERICA = new Country("Central America", new Point (145, 259));
	private static final ICountry VENEZUELA = new Country("Venezuela", new Point(198, 297));
	private static final ICountry BRAZIL = new Country("Brazil", new Point(236, 336));
	private static final ICountry PERU= new Country("Peru", new Point(199, 348));
	private static final ICountry ARGENTINA = new Country("Argentina", new Point(211, 390));
	private static final ICountry ICELAND = new Country("Iceland", new Point(269, 103));
	private static final ICountry GREAT_BRITAIN = new Country("Great Britain", new Point(294, 132));
	private static final ICountry WESTERN_EU= new Country("Western Europe", new Point(306, 197));
	private static final ICountry NORTHERN_EU = new Country("Northern Europe", new Point(361, 140));
	private static final ICountry SOUTHERN_EU = new Country("Southern Europe", new Point(379, 175));
	private static final ICountry SCANDINAVIA = new Country("Scandinavia", new Point(368, 90));
	private static final ICountry UKRAINE = new Country("Ukraine", new Point(436, 135));
	private static final ICountry NORTH_AFRICA = new Country("North Africa", new Point(316, 277));
	private static final ICountry EGYPT = new Country("Egypt", new Point(368, 245));
	private static final ICountry CONGO = new Country("Congo", new Point(369, 327));
	private static final ICountry EAST_AFRICA = new Country("East Africa", new Point(416, 308));
	private static final ICountry SOUTH_AFRICA = new Country("South Africa", new Point(376, 388));
	private static final ICountry MADAGASCAR = new Country("Madagascar", new Point(440, 383));
	private static final ICountry URAL = new Country("Ural", new Point(497, 114));
	private static final ICountry SIBERIA = new Country("Siberia", new Point(550, 106));
	private static final ICountry YAKUTSK = new Country("Yakutsk", new Point(602, 82));
	private static final ICountry KAMCHATKA = new Country("Kamchatka", new Point(639, 111));
	private static final ICountry IRKUTSK = new Country("Irkutsk", new Point(596, 133));
	private static final ICountry AFGHANISTAN = new Country("Afghanistan", new Point(493, 186));
	private static final ICountry CHINA = new Country("China", new Point(563, 218));
	private static final ICountry MONGOLIA = new Country("Mongolia", new Point(603, 170));
	private static final ICountry JAPAN = new Country("Japan", new Point(658, 195));
	private static final ICountry MIDDLE_EAST = new Country("Middle East", new Point(442, 242));
	private static final ICountry INDIA = new Country("India", new Point(510, 263));
	private static final ICountry SIAM = new Country("Siam", new Point(568, 270));
	private static final ICountry INDONESIA = new Country("Indonesia", new Point(592, 328));
	private static final ICountry NEW_GUINEA = new Country("New Guinea", new Point(661, 329));
	private static final ICountry WESTERN_AUSTRALIA = new Country("Western Australia", new Point(605, 409));
	private static final ICountry EASTERN_AUSTRALIA = new Country("Eastern Australia", new Point(661, 416));


	RiskMap(IWorld world) {
		addCountries(world);
		addEdges(world);
	}
	
	private static void addCountries(IWorld world) {
		
		world.addCountry(ALASKA);
		world.addCountry(ALBERTA);
		world.addCountry(NORTHWEST_TERRITORY);
		world.addCountry(ONTARIO);
		world.addCountry(WESTERN_US);
		world.addCountry(EASTERN_US);
		world.addCountry(QUEBEC);
		world.addCountry(GREENLAND);
		world.addCountry(CENTRAL_AMERICA);
		world.addCountry(VENEZUELA);
		world.addCountry(BRAZIL);
		world.addCountry(PERU);
		world.addCountry(ARGENTINA);
		world.addCountry(ICELAND);
		world.addCountry(GREAT_BRITAIN);
		world.addCountry(WESTERN_EU);
		world.addCountry(NORTHERN_EU);
		world.addCountry(SOUTHERN_EU);
		world.addCountry(SCANDINAVIA);
		world.addCountry(UKRAINE);
		world.addCountry(NORTH_AFRICA);
		world.addCountry(EGYPT);
		world.addCountry(CONGO);
		world.addCountry(EAST_AFRICA);
		world.addCountry(SOUTH_AFRICA);
		world.addCountry(MADAGASCAR);
		world.addCountry(URAL);
		world.addCountry(SIBERIA);
		world.addCountry(YAKUTSK);
		world.addCountry(KAMCHATKA);
		world.addCountry(IRKUTSK);
		world.addCountry(AFGHANISTAN);
		world.addCountry(CHINA);
		world.addCountry(MONGOLIA);
		world.addCountry(JAPAN);
		world.addCountry(MIDDLE_EAST);
		world.addCountry(INDIA);
		world.addCountry(SIAM);
		world.addCountry(INDONESIA);
		world.addCountry(NEW_GUINEA);
		world.addCountry(WESTERN_AUSTRALIA);
		world.addCountry(EASTERN_AUSTRALIA);
	}
	
	private static void addEdges(IWorld world) {
		world.addEdge(ALASKA, KAMCHATKA);
		world.addEdge(ALASKA, ALBERTA);
		world.addEdge(ALASKA, NORTHWEST_TERRITORY);
		world.addEdge(ALBERTA, NORTHWEST_TERRITORY);
		world.addEdge(ALBERTA, ONTARIO);
		world.addEdge(ALBERTA, WESTERN_US);
		world.addEdge(BRAZIL, ARGENTINA);
		world.addEdge(CHINA, AFGHANISTAN);
		world.addEdge(CHINA, MONGOLIA);
		world.addEdge(CHINA, SIAM);
		world.addEdge(CHINA, SIBERIA);
		world.addEdge(CHINA, URAL);
		world.addEdge(EAST_AFRICA, CONGO);
		world.addEdge(EAST_AFRICA, MADAGASCAR);
		world.addEdge(EAST_AFRICA, MIDDLE_EAST);
		world.addEdge(EASTERN_AUSTRALIA, NEW_GUINEA);
		world.addEdge(EASTERN_US, CENTRAL_AMERICA);
		world.addEdge(EASTERN_US, ONTARIO);
		world.addEdge(EGYPT, NORTH_AFRICA);
		world.addEdge(EGYPT, EAST_AFRICA);
		world.addEdge(EGYPT, MIDDLE_EAST);
		world.addEdge(GREAT_BRITAIN, NORTHERN_EU);
		world.addEdge(GREAT_BRITAIN, WESTERN_EU);
		world.addEdge(ICELAND, GREAT_BRITAIN);
		world.addEdge(ICELAND, GREENLAND);
		world.addEdge(INDIA, AFGHANISTAN);
		world.addEdge(INDIA, CHINA);
		world.addEdge(INDIA, SIAM);
		world.addEdge(INDONESIA, NEW_GUINEA);
		world.addEdge(INDONESIA, SIAM);
		world.addEdge(INDONESIA, WESTERN_AUSTRALIA);
		world.addEdge(IRKUTSK, KAMCHATKA);
		world.addEdge(IRKUTSK, MONGOLIA);
		world.addEdge(JAPAN, KAMCHATKA);
		world.addEdge(JAPAN, MONGOLIA);
		world.addEdge(MIDDLE_EAST, AFGHANISTAN);
		world.addEdge(MIDDLE_EAST, INDIA);
		world.addEdge(MIDDLE_EAST, SOUTHERN_EU);
		world.addEdge(MONGOLIA, KAMCHATKA);
		world.addEdge(NORTH_AFRICA, BRAZIL);
		world.addEdge(NORTH_AFRICA, CONGO);
		world.addEdge(NORTH_AFRICA, EAST_AFRICA);
		world.addEdge(NORTHERN_EU, SCANDINAVIA);
		world.addEdge(NORTHERN_EU, SOUTHERN_EU);
		world.addEdge(NORTHERN_EU, WESTERN_EU);
		world.addEdge(NORTHWEST_TERRITORY, GREENLAND);
		world.addEdge(NORTHWEST_TERRITORY, ONTARIO);
		world.addEdge(NORTHWEST_TERRITORY, QUEBEC);
		world.addEdge(PERU, ARGENTINA);
		world.addEdge(PERU, BRAZIL);
		world.addEdge(QUEBEC, EASTERN_US);
		world.addEdge(QUEBEC, GREENLAND);
		world.addEdge(QUEBEC, ONTARIO);
		world.addEdge(SIBERIA, IRKUTSK);
		world.addEdge(SIBERIA, MONGOLIA);
		world.addEdge(SIBERIA, URAL);
		world.addEdge(SIBERIA, YAKUTSK);
		world.addEdge(SOUTH_AFRICA, CONGO);
		world.addEdge(SOUTH_AFRICA, MADAGASCAR);
		world.addEdge(SOUTH_AFRICA, EAST_AFRICA);
		world.addEdge(SOUTHERN_EU, EGYPT);
		world.addEdge(SOUTHERN_EU, NORTH_AFRICA);
		world.addEdge(URAL, AFGHANISTAN);
		world.addEdge(UKRAINE, AFGHANISTAN);
		world.addEdge(UKRAINE, MIDDLE_EAST);
		world.addEdge(UKRAINE, NORTHERN_EU);
		world.addEdge(UKRAINE, SCANDINAVIA);
		world.addEdge(UKRAINE, SOUTHERN_EU);
		world.addEdge(UKRAINE, URAL);
		world.addEdge(VENEZUELA, BRAZIL);
		world.addEdge(VENEZUELA, CENTRAL_AMERICA);
		world.addEdge(VENEZUELA, PERU);
		world.addEdge(WESTERN_AUSTRALIA, EASTERN_AUSTRALIA);
		world.addEdge(WESTERN_AUSTRALIA, NEW_GUINEA);
		world.addEdge(WESTERN_EU, NORTH_AFRICA);
		world.addEdge(WESTERN_EU, SOUTHERN_EU);
		world.addEdge(WESTERN_US, CENTRAL_AMERICA);
		world.addEdge(WESTERN_US, EASTERN_US);
		world.addEdge(WESTERN_US, ONTARIO);
		world.addEdge(YAKUTSK, IRKUTSK);
		world.addEdge(YAKUTSK, KAMCHATKA);
	}
}
